### PR TITLE
fixed upload image be invalid

### LINKED ISSUE #10: upload image fail

### PR DESCRIPTION
**Pull request by Yesifan**
Closes #10

### CODE REVIEW

File: src/content/components/upload.tsx [hunk 1]
```diff
@@ -19,11 +19,13 @@ const App:React.FC<UploadProps> = ({ children, onUpload, ...props }) => {
   const handleClick = useCallback(async () => {
     setLoading(true);
     try {
+      console.log('file');
```
Comment (Yesifan) [inline src/content/components/upload.tsx]: Remove console
